### ISSUE TITLE
USER STORY: Register an account

### ISSUE THREAD

**Issue by EdgarasSp** [EdgarasSp/cyclo-domestique-storefront#12]
As a **customer** I want to **register an account** so that I can **manage my activities on the site**.

## **Tasks**
- [x]  Create profiles app and update settings
- [x]  Create models, forms, views
- [x]  Modify Django allauth account templates
- [x]  Add Django url
