### ISSUE TITLE
USER STORY: Navigate the site

### ISSUE THREAD

**Issue by EdgarasSp** [EdgarasSp/cyclo-domestique-storefront#20]
As a **customer** I want to **navigate the site** so that I **know what products the site sells and is about**.

## **Tasks**
- [x]  Create base functionality with navigation links
- [x]  Create home app and render the home page
- [x]  Create separate main navigation
- [x]  Create mobile to navigation
- [x]  Add Bootstrap styling
