### ISSUE TITLE
USER STORY: View product list

### ISSUE THREAD

**Issue by EdgarasSp** [EdgarasSp/cyclo-domestique-storefront#24]
As a **customer** I want to **view the list of products** so that I **know what product the site sells**.

## **Tasks**
- [x]  Create fixtures for the products, categories and divisions
- [x]  Create product models, views, template and urls
- [x]  Create product responsive cards
