### ISSUE TITLE
USER STORY: Site info messages for actions

### ISSUE THREAD

**Issue by EdgarasSp** [EdgarasSp/cyclo-domestique-storefront#28]
As a **customer** I want to **view messages** so that I know **my activities when updating my shopping basket or make a payment**.

## **Tasks**
- [x]  Add Bootstrap toasts templates
- [x]  Add content and styling to the message container
- [x]  Basket previews on hover
