### ISSUE TITLE
USER STORY: Admin add, update and delete product

### ISSUE THREAD

**Issue by EdgarasSp** [EdgarasSp/cyclo-domestique-storefront#3]
As a **shop owner** I want to **add, update and delete product** so that I can **update, add new product or delete unavailable product on the site**.

## **Tasks**
- [x]  Register products in admin panel
- [x]   Manage products in site invetory
- [x]  Create product form, view, template and urls
