### ISSUE TITLE
USER STORY: Add and delete product in the shopping basket

### ISSUE THREAD

**Issue by EdgarasSp** [EdgarasSp/cyclo-domestique-storefront#30]
As a **customer** I want to **add or delete products from the shopping basket** so that I **know what products and the amount of products and cost**.

## **Tasks**
- [x]  Add quantity form and views to the shopping basket page
- [x]  Add functionality to handle add product to the shopping basket
- [x]  Add functionality to handle remove product from the shopping basket
