### ISSUE TITLE
USER STORY: View the total product in the shopping basket 

### ISSUE THREAD

**Issue by EdgarasSp** [EdgarasSp/cyclo-domestique-storefront#31]
As a **customer** I want to **view the products in my shopping basket** so that I **know what I'm purchasing and the total cost for the products**.

## **Tasks**
- [x]  Add functionality to handle the total in the shopping basket
- [x]  Add functionality to handle increase decrease qty
- [x]  Add totals aside section
