### ISSUE TITLE
USER STORY: Checkout and payment processor

### ISSUE THREAD

**Issue by EdgarasSp** [EdgarasSp/cyclo-domestique-storefront#35]
As a **registered customer** I want to **checkout and pay online** so that I can **complete the purchase**.

## **Tasks**
- [x] Create checkout app & models
- [x]  Create signals and register order admin
- [x]  Create order form
- [x]  Create views, template and url
- [x]  Setup Stripe
