### ISSUE TITLE
USER STORY: Contact form

### ISSUE THREAD

**Issue by EdgarasSp** [EdgarasSp/cyclo-domestique-storefront#39]
As a **user** I can **fill out and submit a contact form** so that I can **send queries or feedback**.

## **Tasks**
- [x]  Create contact form
- [x]  Add link to Contact Us form in navigation bar
- [x]  Add  confirmation message upon successful submission of form
