### ISSUE TITLE
USER STORY: View Social account

### ISSUE THREAD

**Issue by EdgarasSp** [EdgarasSp/cyclo-domestique-storefront#44]
As a **customer** I want to **view shops social account** so that I can **share, view and contact shop**.

## **Tasks**
- [ ] Enable post comments
- [ ] Enable post sharing
- [ ] Enable Direct Messaging
