### ISSUE TITLE
USER STORY: Setup SEO meta

### ISSUE THREAD

**Issue by EdgarasSp** [EdgarasSp/cyclo-domestique-storefront#45]
As a **shop owner** I want to **setup SEO** so I can **ensure website is indexed high on the google searches results**.

## **Tasks**
- [x] Setup SEO meta
- [x] Update alt attributes
- [x] setup external links
