### ISSUE TITLE
USER STORY: Admin view edit orders

### ISSUE THREAD

**Issue by EdgarasSp** [EdgarasSp/cyclo-domestique-storefront#7]
As a **shop owner** I want to **view site orders and status** so that I can **confirm order details and update order status**.

## **Tasks**
- [x]  Create view, template and url 
- [x]  Add view order confirmation view 
- [x]  Add update status view for order.
