### ISSUE TITLE
USER STORY: Admin view edit messages

### ISSUE THREAD

**Issue by EdgarasSp** [EdgarasSp/cyclo-domestique-storefront#8]
As a **shop owner** I want to **view site messages and status** so that I can **read message details and update message status**.

## **Tasks**
- [x]  Create view, template and url,
- [x]  Add view message view,
- [x]  Add update message status view for order.
